### ISSUE TITLE
Possible free(nullptr)

### ISSUE THREAD

**Issue by derzhavin3016** [yuphia/onegin#14]
https://github.com/yuphia/onegin/blob/8382ae755591328bfbc08f78c6f7e4a70d67fbe1/sort.c#L71

**Comment by derzhavin3016** [comment]
If you can’t allocate memory, you should immediately return from function

**Comment by derzhavin3016** [comment]
Do you know, what happens if I call `free(NULL)`?

**Comment by yuphia** [comment]
If you call free(nullptr) no action occurs.
