### ISSUE TITLE
Refactor error handling

### ISSUE THREAD

**Issue by derzhavin3016** [yuphia/onegin#15]
E.g., you have `calloc` function, which returns `nullptr` in case of lack of memory, and you should handle it.
You do it like
```c++
void *p_val = calloc(...);
if (p_val != nullptr)
{
  // Some code 
}
```
It make code less readable.
What do you think about this variant?
```c++
void *p_val = calloc(...);
if (p_val == nullptr)
  return;

// Some code 

```
In this case, you have less tabs => more readability, because large `if` scope looks so bulky, isn't it?

**Comment by yuphia** [comment]
resolved by commit 48e7879b1dab0319fefd227223f56a0e06e84a35
