### ISSUE TITLE
Cast

### ISSUE THREAD

**Issue by Tako-San** [yuphia/onegin#33]
https://github.com/yuphia/onegin/blob/1be462deb153ac8901df12700143f3b44841c06c/main.cpp#L44

https://github.com/yuphia/onegin/blob/1be462deb153ac8901df12700143f3b44841c06c/main.cpp#L50

Redundant cast to `void *`

**Comment by yuphia** [comment]
Resolved in commit 64bdf3750972b209ccf13c3fc3c15928e1a5a9df
