### ISSUE TITLE
Codestyle problems

### ISSUE THREAD

**Issue by Tako-San** [yuphia/onegin#34]
https://github.com/yuphia/onegin/blob/1be462deb153ac8901df12700143f3b44841c06c/main.cpp#L77-L81

https://github.com/yuphia/onegin/blob/1be462deb153ac8901df12700143f3b44841c06c/main.cpp#L89-L95

You have to keep common codestyle

**Comment by yuphia** [comment]
resolved in commit d466e959700b510118b498f2f20ebbd5aa20c912
